language: objective-c

osx_image: xcode7.1

cache:
    directories:
        - node_modules
        - .nvm

before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

install:
  - npm install -g flow-bin@`node -p "require('fs').readFileSync('.flowconfig', 'utf8').split('[version]')[1].trim()"`
  - npm install

script:
  - npm test
